apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: a2k-procar
  namespace: a2k-procar
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: a2k-procar
  namespaceSelector:
    matchNames:
      - a2k-procar
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http