apiVersion: v1
kind: Service
metadata:
  name: a2k-procar
  namespace: a2k-procar
  labels:
    app: a2k-procar
spec:
  type: ClusterIP
  selector:
    app: a2k-procar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
