[project]
name = "a2k-procar"
version = "0.1.0"
description = "ML project for car price prediction"
readme = "README.md"
authors = ["aakomov"]
license = "MIT"
requires-python = "==3.11.*"
dependencies = [
    "boto3==1.39.12",
    "cryptography==45.0.5",
    "ipykernel>=6.30.0",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pandas>=2.3.2",
    "pymysql==1.1.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
    "scipy>=1.16.0",
    "seaborn>=0.13.2",
    "pyarrow>=16.0.0",
    "pyspark==3.4.0",
    "mlflow",
    "feast",
    "fastapi==0.115.0",
    "uvicorn==0.31.0",
    "pydantic==2.9.2",
    "apache-airflow",
    "confluent-kafka",
    "prometheus-client",
    "jupyter",
    "kafka-python",
    "loguru==0.7.2",
    "invoke==2.2.0",
]