FROM python:3.11.4-slim-bookworm

WORKDIR /app

COPY requirements.txt requirements.txt
COPY requirements-jupyter.txt requirements-jupyter.txt

RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements-jupyter.txt

COPY scripts scripts
RUN chmod +x scripts/*.sh

CMD ["bash", "scripts/entrypoint-jupyter.sh"]
