services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: a2k-procar:dev
    container_name: a2k-procar-dev
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    command: ["bash", "scripts/entrypoint-dev.sh"]

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    image: otus-maas:jupyter
    container_name: otus-maas-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
    command: ["bash", "scripts/entrypoint-jupyter.sh"]
