FROM python:3.11.4-slim-bookworm

WORKDIR /app

COPY requirements-a2k-dev.txt requirements-a2k-dev.txt

RUN pip install --no-cache-dir -r requirements-a2k-dev.txt

COPY scripts scripts
RUN chmod +x scripts/*.sh

ENV PYTHONPATH="/app"

CMD ["bash", "scripts/entrypoint-dev.sh"]
